# Generated by Django 5.0.7 on 2024-07-17 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clocker', '0002_shift_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
