# Generated by Django 5.0.7 on 2024-07-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocker', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.AlterField(
            model_name='clocker',
            name='time_in',
            field=models.DateTimeField(null=True),
        ),
    ]
