# Generated by Django 5.0.7 on 2024-08-26 02:32

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='photos/default_photo.png', upload_to=employee.models.user_directory_path),
        ),
    ]
