# Generated by Django 5.0.7 on 2024-09-21 02:02

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_userprofile_address_alter_userprofile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to=employee.models.user_directory_path),
        ),
    ]
