# Generated by Django 5.0.7 on 2024-09-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('TP', 'Temporary'), ('IN', 'Intern'), ('FR', 'Freelance'), ('CO', 'Consultant'), ('OC', 'On-call'), ('AP', 'Apprentice'), ('CA', 'Casual')], default='FT', max_length=2),
        ),
    ]
