# Generated by Django 5.0.7 on 2024-08-02 08:36

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='members',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=200, null=True),
        ),
    ]
