# Generated by Django 5.0.7 on 2024-08-02 08:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_department_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='members',
        ),
        migrations.AddField(
            model_name='department',
            name='member_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
