# Generated by Django 5.0.7 on 2024-08-28 03:37

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_event_image1_event_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image1',
            field=models.ImageField(default='events/event_1.jpg', upload_to=company.models.event_directory_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, upload_to=company.models.event_directory_path),
        ),
    ]
