# Generated by Django 5.0.7 on 2024-08-02 08:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_department_members_department_member_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='memberss',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], default=list, max_length=200),
        ),
    ]
