# Generated by Django 5.0.7 on 2024-08-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_department_memberss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='member_list',
        ),
        migrations.RemoveField(
            model_name='department',
            name='memberss',
        ),
    ]
