# Generated by Django 5.0.7 on 2024-09-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_event_media_file_alter_event_media_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_media',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10),
        ),
    ]
