# Generated by Django 5.0.7 on 2024-09-21 02:32

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_event_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hero_image1',
            field=models.ImageField(blank=True, null=True, upload_to=company.models.hero_directory_path),
        ),
        migrations.AddField(
            model_name='company',
            name='hero_image2',
            field=models.ImageField(blank=True, null=True, upload_to=company.models.hero_directory_path),
        ),
        migrations.AddField(
            model_name='company',
            name='hero_image3',
            field=models.ImageField(blank=True, null=True, upload_to=company.models.hero_directory_path),
        ),
        migrations.AddField(
            model_name='company',
            name='hero_image4',
            field=models.ImageField(blank=True, null=True, upload_to=company.models.hero_directory_path),
        ),
        migrations.AddField(
            model_name='company',
            name='hero_image5',
            field=models.ImageField(blank=True, null=True, upload_to=company.models.hero_directory_path),
        ),
    ]
