# Generated by Django 5.0.7 on 2024-09-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_event_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_dates',
        ),
    ]
