# Generated by Django 5.0.7 on 2024-09-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_event_event_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
