# Generated by Django 5.0.7 on 2024-10-02 05:07

import company.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_event_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to=company.models.about_directory_path),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CON', 'Contract'), ('INT', 'Internship')], max_length=3)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience_required', models.CharField(max_length=255)),
                ('qualifications', models.TextField()),
                ('responsibilities', models.TextField()),
                ('application_deadline', models.DateField()),
                ('posting_date', models.DateField(auto_now_add=True, null=True)),
                ('application_link', models.URLField(blank=True, null=True)),
                ('application_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employment_status', models.BooleanField(default=True)),
                ('work_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('application_instructions', models.TextField(blank=True, null=True)),
                ('remote_option', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
