# Generated by Django 5.0.7 on 2024-12-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_event_media_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_media',
            name='video_file',
        ),
    ]
