# Generated by Django 5.0.7 on 2025-01-07 02:19

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_remove_event_media_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_media',
            name='file',
            field=models.FileField(upload_to=company.models.event_files_directory_path),
        ),
    ]
